Integrated styled-components in all pages without linear gradients
williamchong256/immersive-sleep pull request #45
Opened 2021-01-05 00:09 UTC by vinaynagappala

2021-01-05 03:34 UTC, vinaynagappala commented
another thing I forgot to mention is that I removed the header from the detailed data page, which means you have to press the data tab button in the navbar to exit a detailed data page. Up to you guys if we should keep it, but I'm looking into making a simple custom header button.

2021-01-06 00:08 UTC, Firius0408 requested changes
I think there are a few changes that should be made before this is merged into frontend.

2021-01-06 00:08 UTC, Firius0408 commented on frontend/dataTab.jsx
>              {item.efficiency}
Adding a space after the colon would probably make the data easier to read

2021-01-06 00:08 UTC, Firius0408 commented on frontend/dataTab.jsx
> +        showsVerticalScrollIndicator={false}
Is there a particular reason you don't want the scroll indicator to show?

2021-01-06 00:08 UTC, Firius0408 commented on frontend/dataTab.jsx
> +      <DataStack.Screen name="Data" component={Data} options={{ headerShown: false }} />
I think the header should be shown here. I don't see why we should aggressively hide the header in our app.

2021-01-06 00:08 UTC, Firius0408 commented on frontend/dataTab.jsx
> +      <DataStack.Screen name="DetailedData" component={DetailedData} options={{ headerShown: false }} />
Header should definitely be shown here. Otherwise there won't be a back button displayed and a clueless user may find themselves stuck in a detailed data page if they don't know to swipe from the left of the screen to go back.

2021-01-06 00:08 UTC, Firius0408 commented on frontend/detailedData.jsx
> +            {item.efficiency}
Again, a space should be put after the colon so that the data is more easily readable.

2021-01-06 00:08 UTC, Firius0408 commented on frontend/homeTabs.jsx
> +              color: (opacity = 1) => `rgba(0,0,0, ${opacity})`,
This line contains an unnecessary argument `opacity`. @samika1 is there a particular reason you implemented the chart in this way?
```suggestion
              color: () => 'rgba(0,0,0,1)',
```

2021-01-06 00:08 UTC, Firius0408 commented on frontend/homeTabs.jsx
>        />
The moon icon here is ever so slightly off center

<img width="478" alt="image" src="https://user-images.githubusercontent.com/3270324/103712978-01cbd880-4f70-11eb-9a6e-8002c0c016d5.png">

2021-01-06 08:20 UTC, Firius0408 commented on frontend/settingsTab.jsx
> +    <SettingsStack.Navigator>
Is there a particular reason you removed the initialRouteName?

2021-01-06 08:31 UTC, Firius0408 commented on frontend/settingsTab.jsx
> +      <SettingsStack.Screen name="Time Zone" component={TimeZone} options={{ headerTransparent: true }} />
Because the headerTransparent option is essentially the default options of the child Screens, this option should be raised up to the Navigator.

```suggestion
    <SettingsStack.Navigator screenOptions={{ headerTransparent: true }}>
      <SettingsStack.Screen name="Settings" component={Settings} options={{ headerShown: false }} />
      <SettingsStack.Screen name="Preferences" component={Preferences} />
      <SettingsStack.Screen name="Profile" component={Profile} />
      <SettingsStack.Screen name="Notifications" component={Notifications} />
      <SettingsStack.Screen name="Time Zone" component={TimeZone} />
```

2021-01-08 22:24 UTC, vinaynagappala commented on frontend/dataTab.jsx
> +      <DataStack.Screen name="Data" component={Data} options={{ headerShown: false }} />
I hid this header because it would be redundant with the page Title

2021-01-08 22:25 UTC, vinaynagappala commented on frontend/dataTab.jsx
> +        showsVerticalScrollIndicator={false}
not really lol, I thought it was unnecessary

2021-01-08 22:45 UTC, Firius0408 approved these changes
Looks good!

2021-01-08 22:45 UTC, Firius0408 commented on frontend/dataTab.jsx
>              {item.duration}
A cleaner way would be to use string interpolation, but it doesn't really make a difference tbh
```suggestion
            {` ${item.duration}`}
```

2021-01-08 22:45 UTC, Firius0408 commented on frontend/detailedData.jsx
>              {item.heartRate}
Similar tip as in dataTab.jsx if you want to make that change

2021-01-08 22:47 UTC, Firius0408 commented on frontend/homeTabs.jsx
> +              color: (opacity = 1) => `rgba(0,0,0, ${opacity})`,
@vinaynagappala You might also wanna consider committing this to remove the unnecessary argument.

2021-01-08 22:52 UTC, Firius0408 commented on frontend/dataTab.jsx
>              {item.duration}
@vinaynagappala lol I only suggested for one of the elements but if you're gonna apply it you should apply it to all of them, both in data tab and detailed data page, for consistency

2021-01-08 22:56 UTC, Firius0408 approved these changes

2021-01-08 22:56 UTC, merged